import type { Team, Issue, Task, ActivityLog, Location, Organization, OrgSettings } from './types';

export const MOCK_ORG: Organization = {
  id: 'org-1',
  name: 'Meridian Properties Group',
  industry: 'Facility Management',
  locations: ['HQ Tower – Floor 1-10', 'Annex Building A', 'Annex Building B', 'Parking Garage'],
  working_hours: 'Mon–Fri 07:00–19:00, On-call 24/7',
  escalation_rules: 'Critical issues escalate to Ops Manager after 15 min, Manager on call after 30 min',
  default_priority_rules: 'Safety incidents = Critical. Guest-visible issues = High. Maintenance = Medium.',
  ai_instructions: 'Be concise and action-oriented. Always suggest the most direct resolution first.',
  created_at: '2024-01-15T08:00:00Z',
};

export const MOCK_ORG_SETTINGS: OrgSettings = {
  company_name: 'Meridian Properties Group',
  industry: 'Facility Management',
  operating_locations: 'HQ Tower (10 floors), Annex Building A, Annex Building B, Parking Garage',
  available_teams: 'Maintenance, HVAC, Electrical, Cleaning, Security, IT Support',
  working_hours: 'Mon–Fri 07:00–19:00, On-call 24/7',
  escalation_rules: 'Critical → Ops Manager after 15 min. Ops Manager → Director after 30 min.',
  default_priority_rules: 'Safety = Critical. Guest/tenant-facing = High. Preventive = Medium/Low.',
  ai_tone: 'professional',
  ai_instructions: 'Be concise and action-oriented. Prioritize tenant impact and safety.',
};

export const MOCK_TEAMS: Team[] = [
  {
    id: 'team-maintenance',
    org_id: 'org-1',
    name: 'Maintenance',
    specialty: 'General repairs, plumbing, carpentry',
    color: '#3b82f6',
    members: [
      { id: 'tm-1', team_id: 'team-maintenance', name: 'Marco Ritter', role: 'Lead Technician', email: 'marco@meridian.io', available: true },
      { id: 'tm-2', team_id: 'team-maintenance', name: 'Elena Kowalski', role: 'Technician', email: 'elena@meridian.io', available: true },
      { id: 'tm-3', team_id: 'team-maintenance', name: 'Piotr Braun', role: 'Technician', email: 'piotr@meridian.io', available: false },
    ],
  },
  {
    id: 'team-hvac',
    org_id: 'org-1',
    name: 'HVAC',
    specialty: 'Air conditioning, heating, ventilation',
    color: '#06b6d4',
    members: [
      { id: 'th-1', team_id: 'team-hvac', name: 'Sven Larsson', role: 'HVAC Engineer', email: 'sven@meridian.io', available: true },
      { id: 'th-2', team_id: 'team-hvac', name: 'Fatima Al-Rashid', role: 'HVAC Technician', email: 'fatima@meridian.io', available: true },
    ],
  },
  {
    id: 'team-electrical',
    org_id: 'org-1',
    name: 'Electrical',
    specialty: 'Power systems, lighting, fire systems',
    color: '#f59e0b',
    members: [
      { id: 'te-1', team_id: 'team-electrical', name: 'Klaus Weber', role: 'Master Electrician', email: 'klaus@meridian.io', available: true },
      { id: 'te-2', team_id: 'team-electrical', name: 'Anna Schmidt', role: 'Electrician', email: 'anna@meridian.io', available: false },
    ],
  },
  {
    id: 'team-cleaning',
    org_id: 'org-1',
    name: 'Cleaning',
    specialty: 'Daily cleaning, deep cleaning, waste management',
    color: '#10b981',
    members: [
      { id: 'tc-1', team_id: 'team-cleaning', name: 'Maria Santos', role: 'Cleaning Supervisor', email: 'maria@meridian.io', available: true },
      { id: 'tc-2', team_id: 'team-cleaning', name: 'Jan Novak', role: 'Cleaner', email: 'jan@meridian.io', available: true },
      { id: 'tc-3', team_id: 'team-cleaning', name: 'Linh Tran', role: 'Cleaner', email: 'linh@meridian.io', available: true },
    ],
  },
  {
    id: 'team-security',
    org_id: 'org-1',
    name: 'Security',
    specialty: 'Access control, CCTV, incident response',
    color: '#8b5cf6',
    members: [
      { id: 'ts-1', team_id: 'team-security', name: 'Tobias Müller', role: 'Security Chief', email: 'tobias@meridian.io', available: true },
      { id: 'ts-2', team_id: 'team-security', name: 'Yuki Tanaka', role: 'Security Officer', email: 'yuki@meridian.io', available: true },
    ],
  },
  {
    id: 'team-it',
    org_id: 'org-1',
    name: 'IT Support',
    specialty: 'Network, servers, AV systems, access systems',
    color: '#ec4899',
    members: [
      { id: 'ti-1', team_id: 'team-it', name: 'Dmitri Volkov', role: 'IT Lead', email: 'dmitri@meridian.io', available: true },
    ],
  },
];

export const MOCK_LOCATIONS: Location[] = [
  { id: 'loc-1', org_id: 'org-1', name: 'Floor 1 – Lobby', building: 'HQ Tower', floor: '1' },
  { id: 'loc-2', org_id: 'org-1', name: 'Floor 2 – Open Office', building: 'HQ Tower', floor: '2' },
  { id: 'loc-3', org_id: 'org-1', name: 'Floor 3 – Meeting Rooms', building: 'HQ Tower', floor: '3' },
  { id: 'loc-4', org_id: 'org-1', name: 'Floor 4 – Executive Suite', building: 'HQ Tower', floor: '4' },
  { id: 'loc-5', org_id: 'org-1', name: 'Basement – Technical', building: 'HQ Tower', floor: 'B' },
  { id: 'loc-6', org_id: 'org-1', name: 'Annex A – Ground Floor', building: 'Annex A' },
  { id: 'loc-7', org_id: 'org-1', name: 'Parking Garage – Level 1', building: 'Parking' },
];

export const MOCK_ISSUES: Issue[] = [
  {
    id: 'issue-1',
    org_id: 'org-1',
    title: 'AC not working – Floor 3 meeting rooms',
    source_message: 'AC is not working on floor 3, meeting rooms are getting too hot and there is an event in 45 minutes.',
    category: 'HVAC',
    location: 'Floor 3 – Meeting Rooms',
    priority: 'high',
    status: 'assigned',
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60000).toISOString(),
    task_id: 'task-1',
    created_by: 'dispatcher@meridian.io',
    ai_analysis: {
      title: 'AC failure – Floor 3 meeting rooms (event in 45 min)',
      category: 'HVAC',
      location: 'Floor 3 / Meeting Rooms',
      urgency: 'Immediate – event in 45 minutes',
      priority: 'high',
      deadline: '45 minutes',
      required_team: 'HVAC',
      suggested_action: 'Assign available HVAC technician immediately. Notify event coordinator of situation.',
      summary: 'AC unit failure on Floor 3 affecting meeting rooms. Critical timing due to scheduled event in 45 min.',
      missing_info: ['Exact room numbers', 'Which AC unit (central or split)', 'Event organizer contact'],
      confidence: 0.91,
    },
  },
  {
    id: 'issue-2',
    org_id: 'org-1',
    title: 'Water leak – Floor 2 kitchen area',
    source_message: 'There is water leaking from under the kitchen sink on floor 2. Spreading to the floor already.',
    category: 'Plumbing',
    location: 'Floor 2 – Open Office',
    priority: 'high',
    status: 'in_progress',
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 3600000).toISOString(),
    task_id: 'task-2',
    created_by: 'dispatcher@meridian.io',
  },
  {
    id: 'issue-3',
    org_id: 'org-1',
    title: 'Lighting flickering – Executive Floor 4',
    source_message: 'The lights on the executive floor keep flickering. CEO has a client presentation in 2 hours.',
    category: 'Electrical',
    location: 'Floor 4 – Executive Suite',
    priority: 'critical',
    status: 'open',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60000).toISOString(),
    created_by: 'dispatcher@meridian.io',
  },
  {
    id: 'issue-4',
    org_id: 'org-1',
    title: 'Elevator B out of service',
    source_message: 'Elevator B is showing error code E4. Door opens but doesnt close. Tenants complaining.',
    category: 'Elevator',
    location: 'HQ Tower – All Floors',
    priority: 'high',
    status: 'waiting',
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60000).toISOString(),
    created_by: 'dispatcher@meridian.io',
  },
  {
    id: 'issue-5',
    org_id: 'org-1',
    title: 'Broken window latch – Annex A',
    source_message: 'Window in office 204 (Annex A) cannot be closed properly. Security risk.',
    category: 'Security / Maintenance',
    location: 'Annex A – Ground Floor',
    priority: 'medium',
    status: 'open',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_by: 'dispatcher@meridian.io',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-1',
    org_id: 'org-1',
    issue_id: 'issue-1',
    title: 'AC failure – Floor 3 meeting rooms',
    description: 'AC unit not functioning on Floor 3. Event scheduled in 45 minutes. Rooms overheating.',
    category: 'HVAC',
    location: 'Floor 3 – Meeting Rooms',
    priority: 'high',
    status: 'assigned',
    deadline: new Date(Date.now() + 30 * 60000).toISOString(),
    assigned_team_id: 'team-hvac',
    assigned_team_name: 'HVAC',
    assigned_member_id: 'th-1',
    assigned_member_name: 'Sven Larsson',
    ai_summary: 'AC unit failure on Floor 3 affecting meeting rooms with a live event in 45 min.',
    ai_suggested_action: 'Assign HVAC technician immediately. Notify event coordinator. Prepare temporary fans as fallback.',
    source_message: 'AC is not working on floor 3, meeting rooms are getting too hot and there is an event in 45 minutes.',
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60000).toISOString(),
    created_by: 'dispatcher@meridian.io',
  },
  {
    id: 'task-2',
    org_id: 'org-1',
    issue_id: 'issue-2',
    title: 'Water leak – Floor 2 kitchen',
    description: 'Active water leak from kitchen sink on Floor 2. Already spreading on the floor.',
    category: 'Plumbing',
    location: 'Floor 2 – Open Office',
    priority: 'high',
    status: 'in_progress',
    deadline: new Date(Date.now() + 60 * 60000).toISOString(),
    assigned_team_id: 'team-maintenance',
    assigned_team_name: 'Maintenance',
    assigned_member_id: 'tm-1',
    assigned_member_name: 'Marco Ritter',
    ai_summary: 'Active plumbing leak in kitchen area. Risk of water damage and slip hazard.',
    ai_suggested_action: 'Shut off water supply to the kitchen immediately. Send maintenance team. Place wet floor signs.',
    source_message: 'There is water leaking from under the kitchen sink on floor 2. Spreading to the floor already.',
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 3600000).toISOString(),
    created_by: 'dispatcher@meridian.io',
  },
  {
    id: 'task-3',
    org_id: 'org-1',
    issue_id: 'issue-3',
    title: 'Lighting fault – Executive Floor 4',
    description: 'Flickering lights on executive floor. CEO presentation in 2 hours.',
    category: 'Electrical',
    location: 'Floor 4 – Executive Suite',
    priority: 'critical',
    status: 'open',
    deadline: new Date(Date.now() + 90 * 60000).toISOString(),
    ai_summary: 'Electrical fault causing flickering lights on the executive floor before a critical presentation.',
    ai_suggested_action: 'Dispatch electrician immediately. Check circuit breaker and ballasts. If not fixable in 30 min, prepare alternative room.',
    source_message: 'The lights on the executive floor keep flickering. CEO has a client presentation in 2 hours.',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60000).toISOString(),
    created_by: 'dispatcher@meridian.io',
  },
  {
    id: 'task-4',
    org_id: 'org-1',
    issue_id: 'issue-4',
    title: 'Elevator B – E4 door error',
    description: 'Elevator B displaying E4 error. Door opens but does not close. Manually locked out for safety.',
    category: 'Elevator',
    location: 'HQ Tower – All Floors',
    priority: 'high',
    status: 'waiting',
    assigned_team_id: 'team-maintenance',
    assigned_team_name: 'Maintenance',
    ai_summary: 'Elevator B out of service with door sensor fault. External elevator technician required.',
    ai_suggested_action: 'Lock out elevator B. Notify tenants. Contact elevator service contractor (SL Aufzüge, on-call).',
    source_message: 'Elevator B is showing error code E4. Door opens but doesnt close. Tenants complaining.',
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60000).toISOString(),
    created_by: 'dispatcher@meridian.io',
  },
  {
    id: 'task-5',
    org_id: 'org-1',
    title: 'Monthly HVAC filter inspection – all floors',
    description: 'Scheduled preventive maintenance: HVAC filters to be inspected and replaced where needed.',
    category: 'HVAC',
    location: 'HQ Tower – All Floors',
    priority: 'low',
    status: 'open',
    deadline: new Date(Date.now() + 5 * 86400000).toISOString(),
    assigned_team_id: 'team-hvac',
    assigned_team_name: 'HVAC',
    ai_summary: 'Routine preventive HVAC filter check across all floors.',
    ai_suggested_action: 'Schedule during low-occupancy hours (before 08:00). Allow 3 hours.',
    source_message: 'Monthly preventive maintenance schedule',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_by: 'dispatcher@meridian.io',
  },
  {
    id: 'task-6',
    org_id: 'org-1',
    title: 'Broken window latch – Annex A-204',
    description: 'Window in office 204 cannot close fully. Potential security and weather risk.',
    category: 'Maintenance',
    location: 'Annex A – Ground Floor',
    priority: 'medium',
    status: 'open',
    assigned_team_id: 'team-maintenance',
    assigned_team_name: 'Maintenance',
    ai_summary: 'Window closure failure in Annex A. Security concern, needs same-day repair.',
    ai_suggested_action: 'Send maintenance to assess. Temporary fix with wedge. Replace latch hardware.',
    source_message: 'Window in office 204 (Annex A) cannot be closed properly. Security risk.',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    created_by: 'dispatcher@meridian.io',
  },
  {
    id: 'task-7',
    org_id: 'org-1',
    title: 'Lobby floor cleaning – post event',
    description: 'Deep cleaning of lobby and ground floor corridors after last night\'s event.',
    category: 'Cleaning',
    location: 'Floor 1 – Lobby',
    priority: 'medium',
    status: 'completed',
    assigned_team_id: 'team-cleaning',
    assigned_team_name: 'Cleaning',
    assigned_member_id: 'tc-1',
    assigned_member_name: 'Maria Santos',
    ai_summary: 'Post-event deep cleaning of lobby area.',
    ai_suggested_action: 'Deploy full cleaning crew at 07:00 before business hours.',
    source_message: 'Deep cleaning needed after the gala event last night.',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 3600000).toISOString(),
    created_by: 'dispatcher@meridian.io',
  },
];

export const MOCK_ACTIVITY: ActivityLog[] = [
  {
    id: 'log-1',
    org_id: 'org-1',
    entity_type: 'task',
    entity_id: 'task-1',
    action: 'assigned',
    details: 'Assigned to Sven Larsson (HVAC)',
    created_at: new Date(Date.now() - 20 * 60000).toISOString(),
    created_by: 'dispatcher@meridian.io',
    created_by_name: 'Alex (Dispatcher)',
  },
  {
    id: 'log-2',
    org_id: 'org-1',
    entity_type: 'issue',
    entity_id: 'issue-1',
    action: 'created',
    details: 'New issue created from incoming message',
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
    created_by: 'dispatcher@meridian.io',
    created_by_name: 'Alex (Dispatcher)',
  },
  {
    id: 'log-3',
    org_id: 'org-1',
    entity_type: 'task',
    entity_id: 'task-2',
    action: 'status_changed',
    details: 'Status updated: assigned → in_progress',
    created_at: new Date(Date.now() - 60 * 60000).toISOString(),
    created_by: 'dispatcher@meridian.io',
    created_by_name: 'Alex (Dispatcher)',
  },
  {
    id: 'log-4',
    org_id: 'org-1',
    entity_type: 'task',
    entity_id: 'task-7',
    action: 'completed',
    details: 'Task marked as completed by Maria Santos',
    created_at: new Date(Date.now() - 6 * 3600000).toISOString(),
    created_by: 'tc-1',
    created_by_name: 'Maria Santos',
  },
  {
    id: 'log-5',
    org_id: 'org-1',
    entity_type: 'issue',
    entity_id: 'issue-3',
    action: 'created',
    details: 'Critical issue created – lighting fault executive floor',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    created_by: 'dispatcher@meridian.io',
    created_by_name: 'Alex (Dispatcher)',
  },
];

export const CATEGORIES = [
  'HVAC', 'Plumbing', 'Electrical', 'Elevator', 'Cleaning',
  'Security', 'IT Support', 'Maintenance', 'Safety', 'Other',
];
